apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mipvcprovisioning
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
  volumeName: mipvprovisioning
