apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrafanadep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migrafana 
  template:
    metadata:
      labels:
        app: migrafana
    spec:
      containers:
      - name: grafcontainer 
        image: grafana/grafana:latest
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: mipvcgraf
      - name: grafana-provisioning
        persistentVolumeClaim:
          claimName: mipvcprovisioning
