apiVersion: v1
kind: PersistentVolume
metadata:
  name: mipvprovisioning
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/grafprovisioning"
